name: Update Pac-Man GIF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Pac-Man Game Animation
        run: npm run build-animation  # Sesuaikan dengan skrip build animasi yang kamu punya

      - name: Upload Pac-Man GIF to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: pacman-gif
          path: ./path/to/your/pacman.gif

      - name: Commit and push new Pac-Man GIF
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets/pacman.gif
          git commit -m "Update Pac-Man GIF"
          git push
